version: '3.3'
services:
    namenode:
        build:
            context: ./
            dockerfile: Dockerfile-python
        ports:
            - "5000:5000"   
        networks:
            - servers
        depends_on: 
            - neo4j-database
    neo4j-database:
        build:
            context: ./
            dockerfile: Dockerfile-neo4j
        ports:
            - "7474:7474"
            - "7473:7473"
            - "7687:7687"
        networks:
            - servers

networks:
    servers:
        driver: bridge
    