FROM neo4j:latest
RUN cd plugins &&
    wget https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases/download/3.5.0.3/apoc-4.1.0.2-all.jar &&
    chmod 755 apoc-4.1.0.2-all.jar
EXPOSE 7474 7473 7687
